# Generated by Django 3.0.6 on 2020-06-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
